/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTrafficControllers.Application;

import Classes.Vols;
import Protocole.ACMAP.RequeteACMAP;

/**
 *
 * @author student
 */
public class SelectedVol_AirTrafficControllers extends javax.swing.JFrame {
    private Vols selectedVol;
    private Application_AirTrafficControllers parent;
    /**
     * Creates new form SelectedVol_AirTrafficControllers
     */
    public SelectedVol_AirTrafficControllers() {
        initComponents();
    }
    
    public SelectedVol_AirTrafficControllers(Application_AirTrafficControllers appli,Vols selected){
        initComponents();
        this.parent = appli;
        this.selectedVol = selected;
        this.setTitle(this.selectedVol.StringTable());
        this.AirTrafficControllersGroup.setSelected(this.BusyRB.getModel(), true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AirTrafficControllersGroup = new javax.swing.ButtonGroup();
        BusyPanel = new javax.swing.JPanel();
        BusyRB = new javax.swing.JRadioButton();
        BusyL = new javax.swing.JLabel();
        CheckinOffPanel = new javax.swing.JPanel();
        CheckinOffRB = new javax.swing.JRadioButton();
        CheckinOffL = new javax.swing.JLabel();
        ReadyPanel = new javax.swing.JPanel();
        ReadyRB = new javax.swing.JRadioButton();
        ReadyL = new javax.swing.JLabel();
        ReadyToFlyPanel = new javax.swing.JPanel();
        ReadyToFlyRB = new javax.swing.JRadioButton();
        ReadyToFlyL = new javax.swing.JLabel();
        TakingOffPanel = new javax.swing.JPanel();
        TakingOffRB = new javax.swing.JRadioButton();
        TakingOffL = new javax.swing.JLabel();
        FlyingPanel = new javax.swing.JPanel();
        FlyingRB = new javax.swing.JRadioButton();
        FlyingL = new javax.swing.JLabel();
        NextStepButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BusyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(BusyRB);
        BusyRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BusyL.setText("BUSY");
        BusyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout BusyPanelLayout = new javax.swing.GroupLayout(BusyPanel);
        BusyPanel.setLayout(BusyPanelLayout);
        BusyPanelLayout.setHorizontalGroup(
            BusyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BusyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BusyPanelLayout.createSequentialGroup()
                .addComponent(BusyL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BusyPanelLayout.setVerticalGroup(
            BusyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusyPanelLayout.createSequentialGroup()
                .addComponent(BusyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BusyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckinOffPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(CheckinOffRB);

        CheckinOffL.setText("CHECKIN_OFF");
        CheckinOffL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CheckinOffPanelLayout = new javax.swing.GroupLayout(CheckinOffPanel);
        CheckinOffPanel.setLayout(CheckinOffPanelLayout);
        CheckinOffPanelLayout.setHorizontalGroup(
            CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                .addGroup(CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckinOffL)
                    .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CheckinOffRB)))
                .addGap(0, 0, 0))
        );
        CheckinOffPanelLayout.setVerticalGroup(
            CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                .addComponent(CheckinOffL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckinOffRB))
        );

        ReadyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(ReadyRB);

        ReadyL.setText("READY");
        ReadyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ReadyPanelLayout = new javax.swing.GroupLayout(ReadyPanel);
        ReadyPanel.setLayout(ReadyPanelLayout);
        ReadyPanelLayout.setHorizontalGroup(
            ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyPanelLayout.createSequentialGroup()
                .addGroup(ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReadyL)
                    .addGroup(ReadyPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ReadyRB)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReadyPanelLayout.setVerticalGroup(
            ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyPanelLayout.createSequentialGroup()
                .addComponent(ReadyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadyRB))
        );

        ReadyToFlyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(ReadyToFlyRB);

        ReadyToFlyL.setText("READY_TO_FLY");
        ReadyToFlyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ReadyToFlyPanelLayout = new javax.swing.GroupLayout(ReadyToFlyPanel);
        ReadyToFlyPanel.setLayout(ReadyToFlyPanelLayout);
        ReadyToFlyPanelLayout.setHorizontalGroup(
            ReadyToFlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addComponent(ReadyToFlyL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ReadyToFlyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReadyToFlyPanelLayout.setVerticalGroup(
            ReadyToFlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addComponent(ReadyToFlyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadyToFlyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TakingOffPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(TakingOffRB);

        TakingOffL.setText("TAKING_OFF");
        TakingOffL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TakingOffPanelLayout = new javax.swing.GroupLayout(TakingOffPanel);
        TakingOffPanel.setLayout(TakingOffPanelLayout);
        TakingOffPanelLayout.setHorizontalGroup(
            TakingOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addComponent(TakingOffL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TakingOffRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TakingOffPanelLayout.setVerticalGroup(
            TakingOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addComponent(TakingOffL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TakingOffRB)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FlyingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(FlyingRB);

        FlyingL.setText("FLYING");
        FlyingL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout FlyingPanelLayout = new javax.swing.GroupLayout(FlyingPanel);
        FlyingPanel.setLayout(FlyingPanelLayout);
        FlyingPanelLayout.setHorizontalGroup(
            FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlyingPanelLayout.createSequentialGroup()
                .addGroup(FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlyingL)
                    .addGroup(FlyingPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(FlyingRB)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FlyingPanelLayout.setVerticalGroup(
            FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlyingPanelLayout.createSequentialGroup()
                .addComponent(FlyingL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlyingRB)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        NextStepButton.setText("Stop CheckIn");
        NextStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BusyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckinOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NextStepButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReadyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReadyToFlyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TakingOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlyingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CheckinOffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BusyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(ReadyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReadyToFlyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(TakingOffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FlyingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NextStepButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepButtonActionPerformed
        // TODO add your handling code here:
        RequeteACMAP req;
        if(this.AirTrafficControllersGroup.isSelected( this.BusyRB.getModel())){
            this.NextStepButton.setText("Vérifier chargement baggages");
            this.AirTrafficControllersGroup.setSelected(this.CheckinOffRB.getModel(), true);
            req = new RequeteACMAP(RequeteACMAP.REQUEST_CHECKIN_OFF);
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.CheckinOffRB.getModel())){
            this.NextStepButton.setText("Sélectionner une piste");
            this.AirTrafficControllersGroup.setSelected(this.ReadyRB.getModel(), true);
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.ReadyRB.getModel())){
         this.NextStepButton.setText("Autoriser à décoller");
            this.AirTrafficControllersGroup.setSelected(this.ReadyToFlyRB.getModel(), true);
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.ReadyToFlyRB.getModel())){
         this.NextStepButton.setText("Valider décollage");
            this.AirTrafficControllersGroup.setSelected(this.TakingOffRB.getModel(), true);
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.TakingOffRB.getModel())){
            this.NextStepButton.setText("Fermer la fenêtre");
            this.AirTrafficControllersGroup.setSelected(this.FlyingRB.getModel(), true);
        }
        else{
            parent.loadVolsArray();
            parent.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_NextStepButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.initLogOut();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AirTrafficControllersGroup;
    private javax.swing.JLabel BusyL;
    private javax.swing.JPanel BusyPanel;
    private javax.swing.JRadioButton BusyRB;
    private javax.swing.JLabel CheckinOffL;
    private javax.swing.JPanel CheckinOffPanel;
    private javax.swing.JRadioButton CheckinOffRB;
    private javax.swing.JLabel FlyingL;
    private javax.swing.JPanel FlyingPanel;
    private javax.swing.JRadioButton FlyingRB;
    private javax.swing.JButton NextStepButton;
    private javax.swing.JLabel ReadyL;
    private javax.swing.JPanel ReadyPanel;
    private javax.swing.JRadioButton ReadyRB;
    private javax.swing.JLabel ReadyToFlyL;
    private javax.swing.JPanel ReadyToFlyPanel;
    private javax.swing.JRadioButton ReadyToFlyRB;
    private javax.swing.JLabel TakingOffL;
    private javax.swing.JPanel TakingOffPanel;
    private javax.swing.JRadioButton TakingOffRB;
    // End of variables declaration//GEN-END:variables
}
