/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author student
 */
public class BDAIRPORTJFrame extends javax.swing.JFrame {

    /**
     * Creates new form BDAIRPORTJFrame
     */
    public BDAIRPORTJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AgentsBT = new javax.swing.JButton();
        AvionsBT = new javax.swing.JButton();
        BilletsBT = new javax.swing.JButton();
        VolsBT = new javax.swing.JButton();
        BaggagesBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Choissisez la table à voir/modifier");

        AgentsBT.setText("Agents");
        AgentsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentsBTActionPerformed(evt);
            }
        });

        AvionsBT.setText("Avions");
        AvionsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvionsBTActionPerformed(evt);
            }
        });

        BilletsBT.setText("Billets");
        BilletsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BilletsBTActionPerformed(evt);
            }
        });

        VolsBT.setText("Vols");
        VolsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolsBTActionPerformed(evt);
            }
        });

        BaggagesBT.setText("Baggages");
        BaggagesBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaggagesBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgentsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AvionsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(BaggagesBT)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BilletsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VolsBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgentsBT)
                            .addComponent(BilletsBT))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AvionsBT)
                            .addComponent(VolsBT)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(BaggagesBT)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvionsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvionsBTActionPerformed
        try {
            // TODO add your handling code here:
            AvionsJFrame AF = new AvionsJFrame();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_AvionsBTActionPerformed

    private void BaggagesBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaggagesBTActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            BaggagesJFrame BF = new BaggagesJFrame();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BaggagesBTActionPerformed

    private void BilletsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BilletsBTActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            BilletsJFrame BF = new BilletsJFrame();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BilletsBTActionPerformed

    private void AgentsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentsBTActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            AgentsJFrame AF = new AgentsJFrame();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_AgentsBTActionPerformed

    private void VolsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolsBTActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VolsJFrame VF = new VolsJFrame();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_VolsBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BDAIRPORTJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BDAIRPORTJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgentsBT;
    private javax.swing.JButton AvionsBT;
    private javax.swing.JButton BaggagesBT;
    private javax.swing.JButton BilletsBT;
    private javax.swing.JButton VolsBT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
