/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import GUI.SelectFrame.SelectBilletJFrame;
import database.utilities.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author student
 */
public class BilletsJFrame extends javax.swing.JFrame {
    private BilletsBean BB;
    /**
     * Creates new form AvionsJFrame
     */
    public void RefreshTable() throws SQLException
    {
        DefaultTableModel dtm = (DefaultTableModel)Tableau.getModel();
        dtm.setRowCount(0);
        int cpt=0;
        ResultSet rs = BB.Select();        
        while(rs.next())
        {
            Vector ligne = new Vector();
            String Id = rs.getString(1);
            ligne.add(Id);
            int IdVol = rs.getInt(2);
            ligne.add(String.valueOf(IdVol));
            int NbPassagers = rs.getInt(3);
            ligne.add(String.valueOf(NbPassagers));
            
            
            dtm.insertRow(dtm.getRowCount(), ligne);
            cpt++;
            System.out.println("Compteur = "+cpt);
        }
        if(cpt == 0)
        {
            System.out.println("Aucun résultat trouvé!! Fermeture de l'application");
            this.dispose();
        }
        CountBaggagesTF.setText(String.valueOf(cpt));
    }
    
    public void RefreshTable(ResultSet rs) throws SQLException
    {
        DefaultTableModel dtm = (DefaultTableModel)Tableau.getModel();
        dtm.setRowCount(0);
        int cpt=0;
        while(rs.next())
        {
            Vector ligne = new Vector();
            String Id = rs.getString(1);
            ligne.add(Id);
            int IdVol = rs.getInt(2);
            ligne.add(String.valueOf(IdVol));
            int NbPassagers = rs.getInt(3);
            ligne.add(String.valueOf(NbPassagers));
            
            
            dtm.insertRow(dtm.getRowCount(), ligne);
            cpt++;
            System.out.println("Compteur = "+cpt);
        }
        if(cpt == 0)
        {
            System.out.println("Aucun résultat trouvé!! Fermeture de l'application");
            this.dispose();
        }
        CountBaggagesTF.setText(String.valueOf(cpt));
    }
    
    public BilletsJFrame() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setTitle("Billets");
        int cpt = 0;
        BB = new BilletsBean();
        ResultSet rs = BB.SelectCount();
        while(rs.next())
            CountBaggagesTF.setText(String.valueOf(rs.getInt("total")));
        
        rs = BB.Select();        
        while(rs.next())
        {
            Vector ligne = new Vector();
            String Id = rs.getString(1);
            ligne.add(Id);
            int IdVol = rs.getInt(2);
            ligne.add(String.valueOf(IdVol));
            int NbPassagers = rs.getInt(3);
            ligne.add(String.valueOf(NbPassagers));
            
            
            DefaultTableModel dtm = (DefaultTableModel)Tableau.getModel();
            dtm.insertRow(dtm.getRowCount(), ligne);
            cpt++;
            System.out.println("Compteur = "+cpt);
        }
        if(cpt == 0)
        {
            System.out.println("Aucun résultat trouvé!! Fermeture de l'application");
            this.dispose();
        }
        rs = BB.SelectCount();
        System.out.println("SelectCount()");
        
        while(rs.next())
            CountBaggagesTF.setText(String.valueOf(rs.getInt("total")));
        this.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tableau = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CountBaggagesTF = new javax.swing.JTextField();
        SELECTBT = new javax.swing.JButton();
        UPDATEBT = new javax.swing.JButton();
        INSERTBT = new javax.swing.JButton();
        DELETEBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vol", "Passagers"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tableau);

        jLabel1.setText("Nombre de billets :");

        CountBaggagesTF.setEditable(false);
        CountBaggagesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountBaggagesTFActionPerformed(evt);
            }
        });

        SELECTBT.setText("SELECT");
        SELECTBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECTBTActionPerformed(evt);
            }
        });

        UPDATEBT.setText("UPDATE");
        UPDATEBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEBTActionPerformed(evt);
            }
        });

        INSERTBT.setText("INSERT");
        INSERTBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTBTActionPerformed(evt);
            }
        });

        DELETEBT.setText("DELETE");
        DELETEBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(CountBaggagesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UPDATEBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SELECTBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INSERTBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DELETEBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CountBaggagesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SELECTBT)
                        .addGap(32, 32, 32)
                        .addComponent(INSERTBT)
                        .addGap(29, 29, 29)
                        .addComponent(UPDATEBT)
                        .addGap(34, 34, 34)
                        .addComponent(DELETEBT)
                        .addGap(90, 90, 90))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CountBaggagesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountBaggagesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountBaggagesTFActionPerformed

    private void SELECTBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECTBTActionPerformed
        // TODO add your handling code here:
        SelectBilletJFrame SBF = new SelectBilletJFrame(BB,this,false);
        SBF.show();
    }//GEN-LAST:event_SELECTBTActionPerformed

    private void UPDATEBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEBTActionPerformed
        // TODO add your handling code here:
        String Id = (String) Tableau.getValueAt(Tableau.getSelectedRow(),0);
        int IdVol = Integer.parseInt((String)Tableau.getValueAt(Tableau.getSelectedRow(), 1));
        int NbPassagers = Integer.parseInt((String)Tableau.getValueAt(Tableau.getSelectedRow(), 2));
        try {
            BB.Update(Id,-1,-1,"",IdVol,NbPassagers);
        } catch (SQLException ex) {
            Logger.getLogger(AvionsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_UPDATEBTActionPerformed

    private void INSERTBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTBTActionPerformed
        // TODO add your handling code here:
        SelectBilletJFrame SBF = new SelectBilletJFrame(BB,this,true);
        SBF.show();
    }//GEN-LAST:event_INSERTBTActionPerformed

    private void DELETEBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEBTActionPerformed
        // TODO add your handling code here:
        String Id = (String) Tableau.getValueAt(Tableau.getSelectedRow(),0);
        
        try{
            ResultSet rs = BB.Select(false, Id, -1,-1);
            while(rs.next())
                rs.deleteRow();
            this.RefreshTable();
        } catch (SQLException ex) {
            Logger.getLogger(AvionsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DELETEBTActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CountBaggagesTF;
    private javax.swing.JButton DELETEBT;
    private javax.swing.JButton INSERTBT;
    private javax.swing.JButton SELECTBT;
    private javax.swing.JTable Tableau;
    private javax.swing.JButton UPDATEBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
