/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.SelectFrame;
import GUI.AgentsJFrame;
import database.utilities.AgentsBean;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author student
 */
public class SelectAgentJFrame extends javax.swing.JFrame {

    private AgentsBean AB;
    private AgentsJFrame AJF;
    private boolean Insert;
    /**
     * Creates new form SelectAvionJFrame
     */
    public SelectAgentJFrame(AgentsBean AB, AgentsJFrame AJF, boolean Insert) {
        initComponents();
        this.AB = AB;
        this.AJF = AJF;
        this.Insert = Insert;
        this.setTitle("Sélection d'agents");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        IdTF = new javax.swing.JTextField();
        IdL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NomL = new javax.swing.JLabel();
        PrenomL = new javax.swing.JLabel();
        PosteL = new javax.swing.JLabel();
        PosteTF = new javax.swing.JTextField();
        NomTF = new javax.swing.JTextField();
        PrenomTF = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IdL.setText("Id:");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NomL.setText("Nom:");

        PrenomL.setText("Prénom:");

        PosteL.setText("Poste:");

        PosteTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosteTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PrenomL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PrenomTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PosteL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PosteTF)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NomL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomTF)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(IdTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomL))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrenomL)
                    .addComponent(PrenomTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosteL)
                    .addComponent(PosteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ResultSet rs;
            int Id;
            if(IdTF.getText().isEmpty())
                Id =0;
            else
                Id = Integer.parseInt(IdTF.getText());
            
            if(Insert)
            {

                if(Id == 0)
                    System.out.println("L'id n'est pas valide!!");
                else
                {
                    ResultSet rsCompte = AB.Select(true,Id,"","","");
                    int Compte = 0;
                    while(rsCompte.next())
                        Compte = rsCompte.getInt("total");
                    System.out.println("Compte = "+Compte);
                    if(Compte > 0)
                        System.out.println("L'id n'est pas valide!!");
                    else
                    {
                        rs = AB.Select();
                        rs.moveToInsertRow();
                        rs.updateInt(1,Id);
                        rs.updateString(2,NomTF.getText());
                        rs.updateString(3,PrenomTF.getText());
                        rs.updateString(4,PosteTF.getText());
                        rs.insertRow();
                        AJF.RefreshTable(rs);
                    }
                }
                this.dispose();                  
            }
            else
            {

                rs = AB.Select(false, Id,NomTF.getText(),PrenomTF.getText(), PosteTF.getText());
                AJF.RefreshTable(rs);
                this.dispose();
                // TODO add your handling code here:
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectAgentJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PosteTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosteTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosteTFActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdL;
    private javax.swing.JTextField IdTF;
    private javax.swing.JLabel NomL;
    private javax.swing.JTextField NomTF;
    private javax.swing.JLabel PosteL;
    private javax.swing.JTextField PosteTF;
    private javax.swing.JLabel PrenomL;
    private javax.swing.JTextField PrenomTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
