/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.SelectFrame;
import GUI.BaggagesJFrame;
import database.utilities.BaggagesBean;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author student
 */
public class SelectBaggageJFrame extends javax.swing.JFrame {

    private BaggagesBean BB;
    private BaggagesJFrame BJF;
    private boolean Insert;
    /**
     * Creates new form SelectAvionJFrame
     */
    public SelectBaggageJFrame(BaggagesBean BB, BaggagesJFrame BJF, boolean Insert) {
        initComponents();
        this.BB = BB;
        this.BJF = BJF;
        this.Insert = Insert;
        this.setTitle("Sélection de baggages");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        IdTF = new javax.swing.JTextField();
        IdL = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        NomL = new javax.swing.JLabel();
        BilletTF = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IdL.setText("Id:");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        NomL.setText("Billet :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NomL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BilletTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(IdL)
                                .addGap(23, 23, 23)
                                .addComponent(IdTF, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BilletTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomL))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ResultSet rs;
            int Id;
            if(IdTF.getText().isEmpty())
                Id =0;
            else
                Id = Integer.parseInt(IdTF.getText());
            
            if(Insert)
            {

                if(Id == 0)
                    System.out.println("L'id n'est pas valide!!");
                else
                {
                    ResultSet rsCompte = BB.Select(true,Id,"");
                    int Compte = 0;
                    while(rsCompte.next())
                        Compte = rsCompte.getInt("total");
                    System.out.println("Compte = "+Compte);
                    if(Compte > 0)
                        System.out.println("L'id n'est pas valide!!");
                    else
                    {
                        rs = BB.Select();
                        rs.moveToInsertRow();
                        rs.updateInt(1,Id);
                        rs.updateString(2,BilletTF.getText());
                        rs.insertRow();
                        BJF.RefreshTable(rs);
                    }
                }
                this.dispose();                  
            }
            else
            {

                rs = BB.Select(false, Id,BilletTF.getText());
                BJF.RefreshTable(rs);
                this.dispose();
                // TODO add your handling code here:
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectBaggageJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BilletTF;
    private javax.swing.JLabel IdL;
    private javax.swing.JTextField IdTF;
    private javax.swing.JLabel NomL;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
