/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTrafficControllers.Application;

import Classes.Lanes;
import Classes.Vols;
import Protocole.ACMAP.ReponseACMAP;
import Protocole.ACMAP.RequeteACMAP;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author student
 */
public class SelectedVol_AirTrafficControllers extends javax.swing.JFrame {
    private Vols selectedVol;
    private Application_AirTrafficControllers parent;
    private Lanes[] LanesArray;
    private Lanes selectedLane;
    /**
     * Creates new form SelectedVol_AirTrafficControllers
     */
    public SelectedVol_AirTrafficControllers() {
        initComponents();
    }
    
    public SelectedVol_AirTrafficControllers(Application_AirTrafficControllers appli,Vols selected){
        initComponents();
        this.parent = appli;
        this.selectedVol = selected;
        this.setTitle(this.selectedVol.StringTable());
        this.AirTrafficControllersGroup.setSelected(this.BusyRB.getModel(), true);
        this.SelectionLaneDialog.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AirTrafficControllersGroup = new javax.swing.ButtonGroup();
        SelectionLaneDialog = new javax.swing.JDialog();
        StopBT = new javax.swing.JButton();
        SelectBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LanesTable = new javax.swing.JTable();
        BusyPanel = new javax.swing.JPanel();
        BusyRB = new javax.swing.JRadioButton();
        BusyL = new javax.swing.JLabel();
        CheckinOffPanel = new javax.swing.JPanel();
        CheckinOffRB = new javax.swing.JRadioButton();
        CheckinOffL = new javax.swing.JLabel();
        ReadyPanel = new javax.swing.JPanel();
        ReadyRB = new javax.swing.JRadioButton();
        ReadyL = new javax.swing.JLabel();
        ReadyToFlyPanel = new javax.swing.JPanel();
        ReadyToFlyRB = new javax.swing.JRadioButton();
        ReadyToFlyL = new javax.swing.JLabel();
        TakingOffPanel = new javax.swing.JPanel();
        TakingOffRB = new javax.swing.JRadioButton();
        TakingOffL = new javax.swing.JLabel();
        FlyingPanel = new javax.swing.JPanel();
        FlyingRB = new javax.swing.JRadioButton();
        FlyingL = new javax.swing.JLabel();
        NextStepButton = new javax.swing.JButton();

        SelectionLaneDialog.setTitle("Sélection Piste");
        SelectionLaneDialog.setSize(new java.awt.Dimension(650, 400));

        StopBT.setText("Arrêter");
        StopBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBTActionPerformed(evt);
            }
        });

        SelectBT.setText("Sélectionner");
        SelectBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBTActionPerformed(evt);
            }
        });

        LanesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pistes"
            }
        ));
        jScrollPane1.setViewportView(LanesTable);

        javax.swing.GroupLayout SelectionLaneDialogLayout = new javax.swing.GroupLayout(SelectionLaneDialog.getContentPane());
        SelectionLaneDialog.getContentPane().setLayout(SelectionLaneDialogLayout);
        SelectionLaneDialogLayout.setHorizontalGroup(
            SelectionLaneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLaneDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectionLaneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionLaneDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(SelectionLaneDialogLayout.createSequentialGroup()
                        .addComponent(StopBT, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SelectBT)))
                .addContainerGap())
        );
        SelectionLaneDialogLayout.setVerticalGroup(
            SelectionLaneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionLaneDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelectionLaneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StopBT)
                    .addComponent(SelectBT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        BusyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(BusyRB);
        BusyRB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BusyL.setText("BUSY");
        BusyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout BusyPanelLayout = new javax.swing.GroupLayout(BusyPanel);
        BusyPanel.setLayout(BusyPanelLayout);
        BusyPanelLayout.setHorizontalGroup(
            BusyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BusyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BusyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BusyPanelLayout.createSequentialGroup()
                .addComponent(BusyL)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BusyPanelLayout.setVerticalGroup(
            BusyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BusyPanelLayout.createSequentialGroup()
                .addComponent(BusyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BusyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckinOffPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(CheckinOffRB);

        CheckinOffL.setText("CHECKIN_OFF");
        CheckinOffL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout CheckinOffPanelLayout = new javax.swing.GroupLayout(CheckinOffPanel);
        CheckinOffPanel.setLayout(CheckinOffPanelLayout);
        CheckinOffPanelLayout.setHorizontalGroup(
            CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                .addGroup(CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckinOffL)
                    .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(CheckinOffRB)))
                .addGap(0, 0, 0))
        );
        CheckinOffPanelLayout.setVerticalGroup(
            CheckinOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckinOffPanelLayout.createSequentialGroup()
                .addComponent(CheckinOffL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckinOffRB))
        );

        ReadyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(ReadyRB);

        ReadyL.setText("READY");
        ReadyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ReadyPanelLayout = new javax.swing.GroupLayout(ReadyPanel);
        ReadyPanel.setLayout(ReadyPanelLayout);
        ReadyPanelLayout.setHorizontalGroup(
            ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyPanelLayout.createSequentialGroup()
                .addGroup(ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReadyL)
                    .addGroup(ReadyPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ReadyRB)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReadyPanelLayout.setVerticalGroup(
            ReadyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyPanelLayout.createSequentialGroup()
                .addComponent(ReadyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadyRB))
        );

        ReadyToFlyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(ReadyToFlyRB);

        ReadyToFlyL.setText("READY_TO_FLY");
        ReadyToFlyL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout ReadyToFlyPanelLayout = new javax.swing.GroupLayout(ReadyToFlyPanel);
        ReadyToFlyPanel.setLayout(ReadyToFlyPanelLayout);
        ReadyToFlyPanelLayout.setHorizontalGroup(
            ReadyToFlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addComponent(ReadyToFlyL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(ReadyToFlyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReadyToFlyPanelLayout.setVerticalGroup(
            ReadyToFlyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReadyToFlyPanelLayout.createSequentialGroup()
                .addComponent(ReadyToFlyL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReadyToFlyRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TakingOffPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(TakingOffRB);

        TakingOffL.setText("TAKING_OFF");
        TakingOffL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout TakingOffPanelLayout = new javax.swing.GroupLayout(TakingOffPanel);
        TakingOffPanel.setLayout(TakingOffPanelLayout);
        TakingOffPanelLayout.setHorizontalGroup(
            TakingOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addComponent(TakingOffL)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TakingOffRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TakingOffPanelLayout.setVerticalGroup(
            TakingOffPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakingOffPanelLayout.createSequentialGroup()
                .addComponent(TakingOffL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TakingOffRB)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FlyingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AirTrafficControllersGroup.add(FlyingRB);

        FlyingL.setText("FLYING");
        FlyingL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout FlyingPanelLayout = new javax.swing.GroupLayout(FlyingPanel);
        FlyingPanel.setLayout(FlyingPanelLayout);
        FlyingPanelLayout.setHorizontalGroup(
            FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlyingPanelLayout.createSequentialGroup()
                .addGroup(FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlyingL)
                    .addGroup(FlyingPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(FlyingRB)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        FlyingPanelLayout.setVerticalGroup(
            FlyingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlyingPanelLayout.createSequentialGroup()
                .addComponent(FlyingL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlyingRB)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        NextStepButton.setText("Stop CheckIn");
        NextStepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStepButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BusyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckinOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(NextStepButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReadyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReadyToFlyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TakingOffPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlyingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CheckinOffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BusyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(ReadyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ReadyToFlyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(TakingOffPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FlyingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NextStepButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextStepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepButtonActionPerformed
        // TODO add your handling code here:
        RequeteACMAP req;
        ReponseACMAP rep = null;
        if(this.AirTrafficControllersGroup.isSelected( this.BusyRB.getModel())){
            //Requête Checkin Off//
            
            req = new RequeteACMAP(RequeteACMAP.REQUEST_CHECKIN_OFF,selectedVol.ID);
            this.parent.sendRequeteACMAP(req);
            
            rep = this.parent.getResponseACMAP();
            if(rep == null){
                System.err.println("La réponse n'a pas été reçue");
            }
            else if(rep.getCode() == ReponseACMAP.CHECKIN_OFF_SENT){
                this.NextStepButton.setText("Vérifier chargement baggages");
                this.AirTrafficControllersGroup.setSelected(this.CheckinOffRB.getModel(), true);
            }
            else{
                System.err.println("La réponse n'est pas reconnue");
            }
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.CheckinOffRB.getModel())){
            //Requete Is Baggage Loaded//
            
            req = new RequeteACMAP(RequeteACMAP.REQUEST_IS_BAGGAGES_LOADED,selectedVol.ID);
            this.parent.sendRequeteACMAP(req);
            
            rep = this.parent.getResponseACMAP();
            if(rep == null){
                System.err.println("La réponse n'a pas été reçue");
            }
            else if(rep.getCode() == ReponseACMAP.BAGGAGES_LOADED){
                this.NextStepButton.setText("Sélectionner une piste");
                this.AirTrafficControllersGroup.setSelected(this.ReadyRB.getModel(), true);
            }
            else if(rep.getCode() == ReponseACMAP.BAGGAGES_NOT_LOADED){
                System.out.println("Les baggages n'ont pas été chargés");
            }

        }
        else if(this.AirTrafficControllersGroup.isSelected(this.ReadyRB.getModel())){
            //Requete Get Lanes
            
            req = new RequeteACMAP(RequeteACMAP.REQUEST_GET_LANES);
            this.parent.sendRequeteACMAP(req);
            
            rep = this.parent.getResponseACMAP();
            if(rep == null){
                System.err.println("La réponse n'a pas été reçue");
            }
            else if(rep.getCode() == ReponseACMAP.SEND_LANES){
                LanesArray = (Lanes[]) rep.getArray();
                this.LoadTableGUI();
                this.SelectionLaneDialog.setVisible(true);
            }
            else if(rep.getCode() == ReponseACMAP.NO_LANE_FREE){
                JOptionPane.showMessageDialog(this, "Il n'y a aucune piste de libre");
            }
            

        }
        else if(this.AirTrafficControllersGroup.isSelected(this.ReadyToFlyRB.getModel())){
            //Pas de Requete physique//
            this.NextStepButton.setText("Valider décollage");
            this.AirTrafficControllersGroup.setSelected(this.TakingOffRB.getModel(), true);
        }
        else if(this.AirTrafficControllersGroup.isSelected(this.TakingOffRB.getModel())){
            //Requete Unlock Lane//
            req = new RequeteACMAP(RequeteACMAP.REQUEST_UNLOCK_LANE,this.selectedLane.idLane);
            this.parent.sendRequeteACMAP(req);
            
            rep = this.parent.getResponseACMAP();
            if(rep == null) System.err.println("La réponse n'a pas été reçue");
            else if(rep.getCode() == ReponseACMAP.UNLOCK_LANE_OK){
                this.NextStepButton.setText("Fermer la fenêtre");
                this.AirTrafficControllersGroup.setSelected(this.FlyingRB.getModel(), true);   
            }
            else if(rep.getCode() == ReponseACMAP.UNLOCK_LANE_KO){
                JOptionPane.showMessageDialog(this, "Le déverrouillage de la piste a échoué!\nVeuillez réessayer ou contacter un technicien");
            }
        }
        else{
            parent.loadVolsArray();
            parent.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_NextStepButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.initLogOut();
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void StopBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopBTActionPerformed
        this.SelectionLaneDialog.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_StopBTActionPerformed

    private void SelectBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBTActionPerformed
        // TODO add your handling code here:
        if(LanesTable.getSelectedRow()== -1)
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une piste");
        else
        {
            //Requete Lock Lanes//
            
            RequeteACMAP req = new RequeteACMAP(RequeteACMAP.REQUEST_LOCK_LANE, LanesArray[LanesTable.getSelectedRow()].idLane);
            this.parent.sendRequeteACMAP(req);
            
            ReponseACMAP rep = this.parent.getResponseACMAP();
            if(rep == null) System.err.println("La réponse n'a pas été reçue");
            else if(rep.getCode() == ReponseACMAP.LOCK_LANE_OK){
                this.NextStepButton.setText("Autoriser à décoller");
                this.AirTrafficControllersGroup.setSelected(this.ReadyToFlyRB.getModel(), true);
                this.SelectionLaneDialog.dispose();
                this.selectedLane = LanesArray[LanesTable.getSelectedRow()];
                JOptionPane.showMessageDialog(this, "La piste suivante a été verrouillée:\n"+this.selectedLane.nameLane);
            }
            else if(rep.getCode() == ReponseACMAP.LOCK_LANE_KO){
                JOptionPane.showMessageDialog(this.SelectionLaneDialog, "La piste sélectionnée a déjà été verouillée.\nVeuillez en sélectionner une autre");
            }
        }
    }//GEN-LAST:event_SelectBTActionPerformed

 private void LoadTableGUI(){
        DefaultTableModel dtm = (DefaultTableModel)this.LanesTable.getModel();
        for(int i = dtm.getRowCount(); i > 0; i--)
        {
            dtm.removeRow(i);
        }
        
        for(int i = 0; i < LanesArray.length; i++)
        {
            String Vol = LanesArray[i].nameLane;
            System.out.println(Vol);
            Vector ligne = new Vector();
            ligne.add(Vol);
            dtm.addRow(ligne);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup AirTrafficControllersGroup;
    private javax.swing.JLabel BusyL;
    private javax.swing.JPanel BusyPanel;
    private javax.swing.JRadioButton BusyRB;
    private javax.swing.JLabel CheckinOffL;
    private javax.swing.JPanel CheckinOffPanel;
    private javax.swing.JRadioButton CheckinOffRB;
    private javax.swing.JLabel FlyingL;
    private javax.swing.JPanel FlyingPanel;
    private javax.swing.JRadioButton FlyingRB;
    private javax.swing.JTable LanesTable;
    private javax.swing.JButton NextStepButton;
    private javax.swing.JLabel ReadyL;
    private javax.swing.JPanel ReadyPanel;
    private javax.swing.JRadioButton ReadyRB;
    private javax.swing.JLabel ReadyToFlyL;
    private javax.swing.JPanel ReadyToFlyPanel;
    private javax.swing.JRadioButton ReadyToFlyRB;
    private javax.swing.JButton SelectBT;
    private javax.swing.JDialog SelectionLaneDialog;
    private javax.swing.JButton StopBT;
    private javax.swing.JLabel TakingOffL;
    private javax.swing.JPanel TakingOffPanel;
    private javax.swing.JRadioButton TakingOffRB;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
