/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IACHAT.Application;

import Protocole.IACOP.ReponseIACOP;
import Protocole.IACOP.RequeteIACOP;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.Security;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

/**
 *
 * @author student
 */
public class Application_JIACHAT extends javax.swing.JFrame {

    private static final int PORT_FLY = 25565;
    private static final String ADDRESS_FLY = "127.0.0.1";
    
    private MulticastSocket ChatSocket = null;
    
    /**
     * Creates new form NewJFrame
     */
    public Application_JIACHAT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessagePanel = new javax.swing.JTextPane();
        ConnectStatusRB = new javax.swing.JRadioButton();
        LoginTF = new javax.swing.JTextField();
        PasswordPF = new javax.swing.JPasswordField();
        ConnectBT = new javax.swing.JButton();
        LoginL = new javax.swing.JLabel();
        PasswordL = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SendBT = new javax.swing.JButton();
        codeL = new javax.swing.JLabel();
        ResponseCB = new javax.swing.JCheckBox();
        CodeTF = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(MessagePanel);

        ConnectStatusRB.setText("Connecté");
        ConnectStatusRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectStatusRBActionPerformed(evt);
            }
        });

        PasswordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordPFActionPerformed(evt);
            }
        });

        ConnectBT.setText("Se Connecter");
        ConnectBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBTActionPerformed(evt);
            }
        });

        LoginL.setText("Login:");

        PasswordL.setText("Mot de passe:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        SendBT.setText("Envoyer");
        SendBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBTActionPerformed(evt);
            }
        });

        codeL.setText("code:");

        ResponseCB.setText("Répondre");
        ResponseCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResponseCBActionPerformed(evt);
            }
        });

        CodeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LoginL))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ConnectBT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ConnectStatusRB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(PasswordL)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ResponseCB, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(codeL)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CodeTF))
                                        .addComponent(SendBT, javax.swing.GroupLayout.Alignment.TRAILING)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginL)
                    .addComponent(PasswordL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConnectBT)
                    .addComponent(ConnectStatusRB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ResponseCB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codeL)
                            .addComponent(CodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(SendBT)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordPFActionPerformed

    private void ConnectBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectBTActionPerformed
        // TODO add your handling code here:
        Security.addProvider(new BouncyCastleProvider());

        String Login = LoginTF.getText();
        String Password = new String(PasswordPF.getPassword());
        
        if(Login.equals("")){
            JOptionPane.showMessageDialog(this, "Veuillez entrer un login");
        }
        else{
            if(Password.equals("")){
                JOptionPane.showMessageDialog(this, "Veuillez entrer un mot de passe");
            }
            else{
                try {
                    Socket cliSock = new Socket(ADDRESS_FLY,PORT_FLY);
                    ObjectOutputStream oos = new ObjectOutputStream(cliSock.getOutputStream());
                    ObjectInputStream ois = new ObjectInputStream(cliSock.getInputStream());
                    
                    RequeteIACOP req = null;

                    try 
                    {
                        MessageDigest pwdSalted;
                        pwdSalted = MessageDigest.getInstance("SHA-1","BC");
                        pwdSalted.update(Login.getBytes());
                        Timestamp today = Timestamp.from(Instant.now());
                        pwdSalted.update(today.toGMTString().getBytes());
                        req = new RequeteIACOP(RequeteIACOP.LOGIN_GROUP, Login, today, pwdSalted.digest(Password.getBytes()) );
                    } 
                    catch (NoSuchAlgorithmException | NoSuchProviderException ex) 
                    {
                        Logger.getLogger(Application_JIACHAT.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    if(req != null){
                        oos.writeObject(req);oos.flush();
                        
                        ReponseIACOP rep = null;
                        try {
                            rep = (ReponseIACOP) ois.readObject();
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Application_JIACHAT.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if(rep != null){
                            if(rep.getCode() == ReponseIACOP.LOGIN_OK){
                                try{
                                    InetAddress groupAddress = InetAddress.getByName((String) rep.getAdresse());
                                    this.ChatSocket = new MulticastSocket((int)rep.getPort());
                                    this.ChatSocket.joinGroup(groupAddress);
                                    this.ConnectStatusRB.setEnabled(true);
                                }catch(IOException e){
                                    System.out.println("Erreur ? ["+e.getMessage()+"]");
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(this, "Le login ou le mot de passe est incorrect");
                            }
                        }
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(Application_JIACHAT.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_ConnectBTActionPerformed

    private void ConnectStatusRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectStatusRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectStatusRBActionPerformed

    private void SendBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SendBTActionPerformed

    private void ResponseCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResponseCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResponseCBActionPerformed

    private void CodeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application_JIACHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application_JIACHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application_JIACHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application_JIACHAT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application_JIACHAT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeTF;
    private javax.swing.JButton ConnectBT;
    private javax.swing.JRadioButton ConnectStatusRB;
    private javax.swing.JLabel LoginL;
    private javax.swing.JTextField LoginTF;
    private javax.swing.JTextPane MessagePanel;
    private javax.swing.JLabel PasswordL;
    private javax.swing.JPasswordField PasswordPF;
    private javax.swing.JCheckBox ResponseCB;
    private javax.swing.JButton SendBT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel codeL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
